version: "3.7"
services:
  mongodb:
    image: mongo:latest
    env_file: .env
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  mongodb_data_container:
