version: "3.7"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/app
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/api --quiet
      interval: 10s
      start_period: 20s
      timeout: 10s
      retries: 5
volumes:
  mongodb_data_container:
