version: "3.7"
services:
  app:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    environment:
      MONGO_HOST: mongodb
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/app
  mongodb:
    image: mongo:latest
    env_file: .env
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/${MONGO_INITDB_DATABASE} --quiet
      interval: 10s
      start_period: 20s
      timeout: 10s
      retries: 5
volumes:
  mongodb_data_container:
